### ISSUE TITLE
Really hard to compile on latest Debian and Ubuntu

### ISSUE THREAD

**Issue by viddypiddy** [kost/dcled#1]
Either i'm an idiot, or this thing is close to impossible to compile without breaking latest debian and/or ubuntu.

```
~/dcled-2.0# make
gcc -g -lm -lhid  dcled.o   -o dcled
dcled.o: In function `send_screen':
/root/dcled-2.0/dcled.c:199: undefined reference to `hid_set_output_report'
/root/dcled-2.0/dcled.c:199: undefined reference to `hid_set_output_report'
/root/dcled-2.0/dcled.c:199: undefined reference to `hid_set_output_report'
/root/dcled-2.0/dcled.c:199: undefined reference to `hid_set_output_report'
dcled.o: In function `open_hiddev':
/root/dcled-2.0/dcled.c:250: undefined reference to `hid_init'
/root/dcled-2.0/dcled.c:254: undefined reference to `hid_new_HIDInterface'
/root/dcled-2.0/dcled.c:264: undefined reference to `hid_force_open'
collect2: ld returned 1 exit status
make: *** [dcled] Error 1
```

I've gotten this far. And tried switching out some libhid versions, but to no avail.

Possible to get this working again? Seems like they both dont have libhid available by default, are they perchance using some other library these days?...

**Comment by philroche** [comment]
I'm getting the very same errors. @viddypiddy were you able to find a work around?

**Comment by viddypiddy** [comment]
Nope, i gave up.. 5 months ago so :-I

**Comment by philroche** [comment]
Looks like I'll be following suit :(

**Comment by kost** [comment]
libhid is not maintained any more in ubuntu and debian:

https://lists.ubuntu.com/archives/ubuntu-devel/2010-November/032180.html

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=496665

**Comment by kost** [comment]
Can you try my latest version on the github? Just commited few fixes which should help in compiling:

git clone https://github.com/kost/dcled.git

In case you don't have libhid, you can get it from this location (worked for me): 
http://libhid.alioth.debian.org/

I have used this SVN version:
svn co svn://svn.debian.org/libhid/trunk libhid-svn

Let me know if it works!

**Comment by philroche** [comment]
@kost - awesome stuff. Working like a charm. Thank you very much.

**Comment by kost** [comment]
Thanks. Closing this issue.

**Comment by viddypiddy** [comment]
Chiming in to say that it works perfectly! Thanks alot!
